---
title: "Real data: Case study"
output: pdf_document
date: "2026-01-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Libraries
library(patchwork)
library(Matrix)

source("../TESSERA_comparison_methods.R")

# Path to figures
figure_path <- "../../figures/real/case_study/"
# Path to data
processed_data_path <- "../../data/processed/"
# Load data (input)
prep_out <- readRDS(file.path(processed_data_path, "prepData_lattice_onlyinteract.rds"))
```

```{r}
# Gene
gene_name <- trimws("ACTA2")
# Load data (output)
out <- readRDS(file.path(processed_data_path, paste0("poisECM_real_natgen_kidney_model_Leroux_gene_", gene_name, ".rds")))
# Debug check for Run-All
if (is.null(names(out$predictions))) {
    stop("The 'out' object has no cell names. Run-All cannot match cells.")
}
```

```{r}
# Sample
sample_to_plot <- trimws("HK3035_ST")

# Extract sample in lists
sample_idx <- which(toupper(names(prep_out$X_list)) == toupper(sample_to_plot))
if (length(sample_idx) == 0) stop("Sample name not found!")

# Extract gene 
gene_idx <- which(toupper(rownames(prep_out$counts_list[[sample_idx]])) == toupper(gene_name))
if (length(gene_idx) == 0) stop("gene name not found!")

# Extract sample cells (in out)
cell_idx <- which(names(out$predictions) %in% rownames(prep_out$X_list[[sample_idx]]))
stopifnot(length(cell_idx) == nrow(prep_out$X_list[[sample_idx]]))
```

```{r}
glm_out <- glm_nb_wrapper(
  lapply(prep_out$counts_list, function (x) {
    x[gene_name, ]
  }),
  prep_out$X_list,
  library_size_list = prep_out$library_size_list
)

# Extract predictions
glm_pred <- predict(glm_out, type = "response")
glm_resid <- Reduce(c, lapply(prep_out$counts_list, function (x) {
  x[gene_name, ]
})) - glm_pred
```

```{r}
plot_df <- data.frame(
  x = prep_out$coords_list[[sample_idx]][, 1],
  y = prep_out$coords_list[[sample_idx]][, 2],
  celltype = prep_out$covariates_list[[sample_idx]]$celltype,
  xpr = as.numeric(prep_out$counts_list[[sample_idx]][gene_idx, ]),
  TESSERA_pred = pmax(0, out$predictions[cell_idx]),
  TESSERA_resid = out$residuals[cell_idx],
  theta_hat = out$theta_hat[cell_idx],
  eta_hat = out$eta_hat[cell_idx],
  phi_hat = out$phi_hat[cell_idx],
  Xbeta = as.numeric(as.matrix(prep_out$X_list[[sample_idx]]) %*% as.numeric(out$beta_hat)),
  glm_pred = pmax(0, glm_pred[cell_idx]),
  glm_resid = glm_resid[cell_idx]
)
```

```{r}
# Cell type colors
set.seed(200)
P26 <- Polychrome::createPalette(26, c("#ff0000", "#00ff00", "#0000ff"))
names(P26) <- unique(plot_df$celltype)

shared_range <- range(c(plot_df$TESSERA_resid, plot_df$glm_resid), na.rm = TRUE)
shared_range_xpr <- range(c(plot_df$xpr, plot_df$TESSERA_pred, plot_df$glm_pred), na.rm = TRUE)

cols_low <- viridis::mako(n = 100, direction = -1)
cols_high <- viridis::rocket(n = 100, direction = 1)
dynamic_colors <- c(cols_low, cols_high)

# Cell type
p1 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color =
                                                     celltype))
p1 <- p1 + ggplot2::geom_point(size = 3) 
p1 <- p1 + ggplot2::scale_colour_manual(name = "Cell type", values = P26) 
p1 <- p1 + ggplot2::theme_bw()
p1 <- p1 + ggplot2::theme(text = ggplot2::element_text(size = 30), legend.text = ggplot2::element_text(size = 10))
p1 <- p1 + ggplot2::guides(colour = ggplot2::guide_legend(override.aes = list(size = 5), ncol = 1))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_celltypes.pdf"), p1, height=8, width = 8, units = "in")

# Expression
p2 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color = xpr))
p2 <- p2 + ggplot2::geom_point(size = 3) 
# Using the viridis scale directly for the rocket palette
p2 <- p2 + viridis::scale_color_viridis(
    name = "Counts, Z",
    option = "rocket",
    # direction = 1 means dark-to-light; use -1 if you want light-to-dark
    direction = 1,
    limits = shared_range_xpr,
    guide = ggplot2::guide_colorbar(
      barheight = ggplot2::unit(10, "cm"),
      ticks.linewidth = 2
    )
  )
p2 <- p2 + ggplot2::theme_bw()
p2 <- p2 + ggplot2::theme(text = ggplot2::element_text(size = 30),
                          legend.title = ggplot2::element_text(margin = ggplot2::margin(b = 10)))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_counts.pdf"), p2, height=8, width = 8, units = "in")

# TESSERA Predictions
p3 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color = TESSERA_pred))
p3 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color = TESSERA_pred))
p3 <- p3 + ggplot2::geom_point(size = 3) 

p3 <- p3 + viridis::scale_color_viridis(
    name = expression(hat(Z)[TESSERA]),
    option = "rocket",
    # direction = 1 means dark-to-light; use -1 if you want light-to-dark
    direction = 1, 
    limits = shared_range_xpr,
    guide = ggplot2::guide_colorbar(
    barheight = ggplot2::unit(10, "cm"),
    ticks.linewidth = 2
    )
  )
p3 <- p3 + ggplot2::theme_bw()
p3 <- p3 + ggplot2::theme(text = ggplot2::element_text(size = 30),
                          legend.title = ggplot2::element_text(margin = ggplot2::margin(b = 10)))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_TESSERA_pred_counts.pdf"), p3, height=8, width = 8, units = "in")

# Spatially varying mean parameter
p4 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color = theta_hat))
p4 <- p4 + ggplot2::geom_point(size = 3) 

p4 <- p4 + ggplot2::scale_color_gradientn(
    name = expression(hat(theta)[TESSERA]),
    colors = dynamic_colors,
    limits = shared_range_xpr,
    # Anchoring the black/dark transition at 0
    values = scales::rescale(c(shared_range_xpr[1], 0, shared_range_xpr[2])),
    guide = ggplot2::guide_colorbar(
      barheight = ggplot2::unit(10, "cm"),
      ticks.linewidth = 2
    )
  )
p4 <- p4 + ggplot2::theme_bw()
p4 <- p4 + ggplot2::theme(text = ggplot2::element_text(size = 30),
                          legend.title = ggplot2::element_text(margin = ggplot2::margin(b = 10)))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_theta.pdf"), p4, height=8, width = 8, units = "in")

# TESSERA residuals
p5 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color = TESSERA_resid))
p5 <- p5 + ggplot2::geom_point(size = 3) 

p5 <- p5 + ggplot2::scale_color_gradientn(
    name = "TESSERA\nresiduals",
    colors = dynamic_colors,
    limits = shared_range,
    # Anchoring the black/dark transition at 0
    values = scales::rescale(c(shared_range[1], 0, shared_range[2])),
    guide = ggplot2::guide_colorbar(
      barheight = ggplot2::unit(10, "cm"),
      ticks.linewidth = 2
    )
  )
p5 <- p5 + ggplot2::theme_bw()
p5 <- p5 + ggplot2::theme(text = ggplot2::element_text(size = 30),
                          legend.title = ggplot2::element_text(margin = ggplot2::margin(b = 20)))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_TESSERA_resid.pdf"), p5, height=8, width = 8, units = "in")

# Spatial random effects
p6 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color =
                                                     phi_hat))
p6 <- p6 + ggplot2::geom_point(size = 3) 

p6 <- p6 + ggplot2::scale_color_gradientn(
    name = expression(hat(phi)[TESSERA]),
    colors = dynamic_colors,
    # Centering the dark transition point at 0
    values = scales::rescale(c(min(plot_df$phi_hat, na.rm = TRUE), 
                               0, 
                               max(plot_df$phi_hat, na.rm = TRUE))),
    guide = ggplot2::guide_colorbar(
      barheight = ggplot2::unit(10, "cm"),
      ticks.linewidth = 2
    )
  )
p6 <- p6 + ggplot2::theme_bw()
p6 <- p6 + ggplot2::theme(text = ggplot2::element_text(size = 30),
                          legend.title = ggplot2::element_text(margin = ggplot2::margin(b = 10)))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_phi.pdf"), p6, height=8, width = 8, units = "in")

# GLM Predictions
p7 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color = glm_pred))
p7 <- p7 + ggplot2::geom_point(size = 3) 

p7 <- p7 + viridis::scale_color_viridis(
    name = expression(paste(hat(Z)[NB], "         ")),
    option = "rocket",
    # direction = 1 means dark-to-light; use -1 if you want light-to-dark
    direction = 1, 
    limits = shared_range_xpr,
    guide = ggplot2::guide_colorbar(
      barheight = ggplot2::unit(10, "cm"),
      ticks.linewidth = 2
    )
  )
p7 <- p7 + ggplot2::theme_bw()
p7 <- p7 + ggplot2::theme(text = ggplot2::element_text(size = 30),
                          legend.title = ggplot2::element_text(margin = ggplot2::margin(b = 10)))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_GLM_NB_pred_counts.pdf"), p7, height=8, width = 8, units = "in")

# GLM residuals
p8 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color = glm_resid))
p8 <- p8 + ggplot2::geom_point(size = 3) 
p8 <- p8 + ggplot2::scale_color_gradientn(
    name = "NB GLM\nresiduals",
    colors = dynamic_colors,
    limits = shared_range,
    # For residuals, we anchor the transition at 0
    values = scales::rescale(c(shared_range[1], 0, shared_range[2])),
    guide = ggplot2::guide_colorbar(
      barheight = ggplot2::unit(10, "cm"),
      ticks.linewidth = 2
    )
  )

p8 <- p8 + ggplot2::theme_bw()
p8 <- p8 + ggplot2::theme(text = ggplot2::element_text(size = 30),
                          legend.title = ggplot2::element_text(margin = ggplot2::margin(b = 20)))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_GLM_NB_resid.pdf"), p8, height=8, width = 8, units = "in")

# Covariate effects
p9 <- ggplot2::ggplot(data = plot_df, ggplot2::aes(x = x, y = y, color = Xbeta))
p9 <- p9 + ggplot2::geom_point(size = 3) 

p9 <- p9 + ggplot2::scale_color_gradientn(
    name = expression(X * hat(beta)[TESSERA]),
    colors = dynamic_colors,
    # rescaler ensures the transition happens exactly at your median
    values = scales::rescale(c(min(plot_df$Xbeta, na.rm=T), 
                               median(plot_df$Xbeta, na.rm=T), 
                               max(plot_df$Xbeta, na.rm=T))),
    guide = ggplot2::guide_colorbar(
      barheight = ggplot2::unit(10, "cm"),
      ticks.linewidth = 2
    )
  )
p9 <- p9 + ggplot2::theme_bw()
p9 <- p9 + ggplot2::theme(text = ggplot2::element_text(size = 30),
                          legend.title = ggplot2::element_text(margin = ggplot2::margin(b = 20)))
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, "_Xbeta.pdf"), p9, height=8, width = 8, units = "in")
```

```{r}
p <- (p1 + p2 + p3 + p7 + p6 + p9 + p5 + p8) + plot_layout(ncol = 4, nrow = 2)
ggplot2::ggsave(paste0(figure_path, "gene_", gene_name, "_sample_", sample_to_plot, ".pdf"), p, height=18, width = 32, units = "in")
```


